### ISSUE TITLE
Finish Input component

### ISSUE THREAD

**Issue by Woutjeee** [Woutjeee/rust-journey#1]
# Overview
finish the component with the following items finished.

## Todo
- [ ] Check if the entered input supports a icon in front of the input.
- [ ] Add support to have icons in front and in the middle of two inputs.
- [ ] Allow multiple spans (icons) to be infront of input field
- [ ] Allow multiple inputs like the following picture.
![image](https://user-images.githubusercontent.com/72391464/229352791-94007561-8066-49f4-b0ef-4626cf6b12c5.png)
- [ ] Allow buttons on a input in front and behind the input.
- [ ] Allow dropdowns on a input in front and behinf the input
